// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3h5TyH5oucAIuBtBt4xTpMDoHUE77eFE',
    appId: '1:401470234441:web:2921c9cf80aa49fb07c498',
    messagingSenderId: '401470234441',
    projectId: 'ai-dictionary-bfdc7',
    authDomain: 'ai-dictionary-bfdc7.firebaseapp.com',
    storageBucket: 'ai-dictionary-bfdc7.firebasestorage.app',
    measurementId: 'G-CZ6R1QNPYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCxZAnjXdMfd2sa3p8eTGeLVl5dHmNYVQ',
    appId: '1:401470234441:android:e67ff0bb18d2ead407c498',
    messagingSenderId: '401470234441',
    projectId: 'ai-dictionary-bfdc7',
    storageBucket: 'ai-dictionary-bfdc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwQcY1PpPwWbjBQXiFg85FxA0z9gS4tVQ',
    appId: '1:401470234441:ios:430148a0a6df299e07c498',
    messagingSenderId: '401470234441',
    projectId: 'ai-dictionary-bfdc7',
    storageBucket: 'ai-dictionary-bfdc7.firebasestorage.app',
    iosBundleId: 'com.example.aiDictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwQcY1PpPwWbjBQXiFg85FxA0z9gS4tVQ',
    appId: '1:401470234441:ios:430148a0a6df299e07c498',
    messagingSenderId: '401470234441',
    projectId: 'ai-dictionary-bfdc7',
    storageBucket: 'ai-dictionary-bfdc7.firebasestorage.app',
    iosBundleId: 'com.example.aiDictionary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3h5TyH5oucAIuBtBt4xTpMDoHUE77eFE',
    appId: '1:401470234441:web:eeff6763851882a407c498',
    messagingSenderId: '401470234441',
    projectId: 'ai-dictionary-bfdc7',
    authDomain: 'ai-dictionary-bfdc7.firebaseapp.com',
    storageBucket: 'ai-dictionary-bfdc7.firebasestorage.app',
    measurementId: 'G-G17KW05NBY',
  );
}
